sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
install: 
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose six coverage requests scikit-learn 
  - pip install coveralls
before_script: 
  # Configure a headless display
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - echo
after_script:
  - echo
notifications:
  email:
    recipients:
      - andy.casey@gmail.com 
    on_success: change
    on_failure: change
